language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "evgenij27-github"
    token:
      secure: "cxcsfvnvjjmEm3so3+LxHBTBZwIRw6g9r6RCC0OB4qeWRDksgQLNrXv1BW0YRDP1oZfn+wa9csiJ7opDxluDsjVeIua9UubZz0wuTw1Aeir3gUVC83UCIkCuOkQiksD2cYympyDRDf/pdB0pz0pJeUd50xGZAbMu2f4KcjRXEKzmeHy5uc9XB/nKD7etOcSaWaLiV3QMfo90+luI1kMNvGKbAGAgBnqen1eEvS8RQ9GUtu+QsM2lyZoiGteCvDelNMpV6S30pA4Kz0NM8fLM/A1uiUTdSUyGnpKwmAaJUmpdnMSs8+jg3xGyLhl7bslEgQPM+Qk91V/EkZa9AOZhyeBqRxb9KqFMMX7YTStUuW6m/v7dF+peLvKCWmM11llsKIksJPxwumyNvGJw1/ZNz2vDvuswhk0BdDk5EES+qub+WqNd8ypUHkl3rMHzzIkJYpyqjbff8xMfBOyFf5AVsEELL/gnMQ2J7mNgXfTQxdmkeom6Vh7JswVYeGYCC8CgefXAgBM9gD+R0TAvw3/H/RrjAvNqut8WVVGl02iYu1nacwTqYfVMxuP+nrCyw2um5N0hUfTkbwhhtAuLAAf3lxxdsp/aGoCCRy2x+V097T74VMlEC823yNKv7N7B1FiSEBCbXc7hsXTEGz6M2QBDVwjkGvR+mKae4cptN6DnhHU="
jdk:
 - oraclejdk8
script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
